In [1]:
import numpy as np

In [2]:
# Criando matriz 3x3

a = np.array([(1,2,3),(4,5,6),(7,8,())])
print(a)

[[1 2 3]
 [4 5 6]]


In [12]:
# Matriz com valor Zero 4x3
c = np.zeros([4,3])

# Matriz com valor Um 4x3
d = np.ones([4,3])

# Matriz quadrada 10x10 com diagonal Principal
e = np.eye(10)

print(c)
print(" ")
print(d)
print(" ")
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [17]:
# Demais Funções da Numpy

maior = a.max()
menor = a.min()
soma = a.sum()
média = a.mean()
DesvPad = a.std()

print("O maior valor da matriz é {}".format(str(maior)))
print("O menor valor da matriz é {}".format(str(menor)))
print("A soma dos valores da matriz é {}".format(str(soma)))
print("A média dos valores da matriz é {}".format(str(média)))
print("O Desvio Padrão é {}".format(str(DesvPad)))

O maior valor da matriz é 6
O menor valor da matriz é 1
A soma dos valores da matriz é 21
A média dos valores da matriz é 3.5
O Desvio Padrão é 1.707825127659933
